### ISSUE TITLE
Can send, but not receive, messages

### ISSUE THREAD

**Issue by klardotsh** [EionRobb/purple-pulsesms#1]
The buddy list populates (even with names if I set `nick_format %full_name`, much like Google Hangouts requires), and I can send folks messages (though, at least in Bitlbee, they show up as `[SoAndSo] is away: Phone`). When they reply, I get nothing in Bitlbee, but do see the message in Pulse SMS's official desktop client. I see nothing particularly interesting in the Bitlbee control channel indicating why this might be the case.

**Comment by EionRobb** [comment]
That's because I'm lazy and haven't implemented that yet.  Oops!

**Comment by EionRobb** [comment]
implemented a polling check for messages... a live stream still to come :)

**Comment by ZedDrebin** [comment]
Seems like it works. Excited about this. I sent a text and the recipient got my message and a string that looks like..

?OTR:AAMC2/kNuQAAAAAAAADEyzGkX1T/aFSnesTBc2x8q05nOEjGJFUgWtTtfFYz0Fba0HY1AY3aAtpkeq4OOCzCrhO0hBpfrI1kwjGoc96Wt00BMfG+/I3RRsAXxVTuu1cvsW+gOm21iofzonLobNWAktW8b0RnJVh3xbYCIUOr0Jv4...... 

(there was more, I did not copy it all... )

**Comment by EionRobb** [comment]
@AVaccNY looks like you tried to start an encrypted OTR conversation over sms. I don't know if that's going to work very well :)
