### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by Akensai** [EionRobb/purple-pulsesms#2]
Think you can compile it for Windows?

**Comment by EionRobb** [comment]
Whoops, I should really write something more useful on the readme with links and stuff.

The plugin gets compiled for windows every time there's a commit, at https://eion.robbmob.com/libpulsesms.dll

**Comment by Akensai** [comment]
> Whoops, I should really write something more useful on the readme with links and stuff.
> 
> The plugin gets compiled for windows every time there's a commit, at https://eion.robbmob.com/libpulsesms.dll

Ah, I thought thats how you had em running but didn't see it anywhere. Cheers.
