### ISSUE TITLE
Are links to images possible?

### ISSUE THREAD

**Issue by uriel1998** [EionRobb/purple-pulsesms#7]
Feature request, I guess?

For example, when I look at Twitter or Mastodon via bitlbee, images are parsed as links to the image, eg.

```
20:06 <natecull> Strings are sequences of strictly non-space characters, underscores are replaced with spaces, slashes are not escapes unless you manually run the s:format word on them.
20:06 <natecull> I'm... not a fan of zero terminated strings though, sorry. That feels like a big mistake. Can that be fixed?
20:06 <natecull>  https://faithcollapsing.com/system/cache/media_attachments/files/105/579/701/807/686/044/original/9827740e1bcd541d.png
```

Whereas receiving an image looks like this:

```
20:06 <betina> : 
```

Forgive my ignorance; is there a way to emit an URL to the resource from the PulseSMS web app, for example?

**Comment by EionRobb** [comment]
Like the SMS messages themselves, images are end-to-end encrypted.  eg https://www.googleapis.com/download/storage/v1/b/messenger-42616.appspot.com/o/d36cec1e7baf1898e82a523ca60130c43e5b5625d3eca37e914a3ff42ecd96ac%2F596058151747519?generation=1594425005777629&alt=media 

Without the decryption keys, its not possible to have a direct link to the image.  There's also no permalink within the pulsesms web app either (it renders them all inline using the decoded image data in a `data:` uri)

Spectrum2 has an option that can host downloaded inline images onto a separate http server... does bitlbee offer something similar?

**Comment by uriel1998** [comment]
No, I don't think so.  That's okay; I'm actually more reassured about the encryption than bothered by the lack of images there.  :)  Thanks for answering!
